{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Installed Memory",
   "type": "stat",
   "description": "Installed Memory of the server",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[$__rate_interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Types",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Sinus",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 9 },
   "targets": [
    { "expr": "my_sinus", "legendFormat": "Sinus" }
   ]
  }
 ]
}