version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.40.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./../config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss:8.5.15
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=prometheusWorkshop
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
    volumes:
      - "./../config/prometheus_source.yml:/etc/grafana/provisioning/datasources/prometheus_source.yml"
    ports:
      - 3000:3000

  code:
    build: ./../images/code/
    container_name: code
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - PASSWORD=prometheusWorkshop
    command: /prometheus/workspace --disable-workspace-trust --disable-getting-started-override --disable-telemetry
    ports:
      - 5000:8080
  
  node-exporter:
    image: prom/node-exporter:v1.4.0
    container_name: node
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor-arm64:v0.46.0
    container_name: cadvisor
    restart: unless-stopped
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
